title: André Rodrigues
show_downloads: "false"
description: I love taking on challenges where we can leverage technology in novel ways to help others in need
github:
  aboutme: aboutme.html
  publications: publications.html
theme: jekyll-theme-architect
