title: André Rodrigues
show_downloads: "false"
description: I received my MSc in 2014 with a dissertation on mobile system wide assistive technology. Currently I am a fourth year PhD student at LASIGE, Faculdade de Ciências da Universidade de Lisboa with the topic Facilitating Smartphone Use for Blind People through a Human-Powered Approach. My research is focused on mobile accessibility working closely with visually impaired people. 

theme: jekyll-theme-architect
